spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: university
        uri: http://${universityServiceHost:127.0.0.1}:8090
        predicates:
            Path=/
        filters:
            TokenRelay=,
            RemoveRequestHeader=Cookie
      - id: student
        uri: http://${studentServiceHost:127.0.0.1}:8091
        predicates:
            Path=/student
        filters:
            TokenRelay=,
            RemoveRequestHeader=Cookie
      - id: auth
        uri: http://${studentServiceHost:127.0.0.1}:9000
        predicates:
            Path=/auth
        filters:
            TokenRelay=,
            RemoveRequestHeader=Cookie
    security:
      oauth2:
        client:
          registration:
            gateway:
              client-secret: secret
              authorization-grant-type: authorization_code
              redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
              client-id: gateway
              scope: openid,resource.read
              provider: spring
          provider:
            spring:
              issuer-uri: http://${authServiceHost:localhost}:8080/auth
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eurekaServiceHost:localhost}:8761/eureka/
