spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: university
          uri: http://${universityServiceHost:localhost}:8090
          predicates:
            Path=/university
          filters:
            TokenRelay=,
            RemoveRequestHeader=Cookie
        - id: student
          uri: http://${studentServiceHost:localhost}:8091
          predicates:
              Path=/student
          filters:
              TokenRelay=,
              RemoveRequestHeader=Cookie
    security:
      oauth2:
        client:
          registration:
            gateway:
              client-secret: secret
              authorization-grant-type: authorization_code
              redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
              client-id: gateway
              scope: openid,resource.read
              provider: spring
          provider:
            spring:
              issuer-uri: http://${authServerHost:localhost}:9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eurekaServiceHost:localhost}:8761/eureka/
